// Code generated by bingen. DO NOT EDIT.

package crypto

import (
	"encoding/binary"

	"github.com/erfanheydarzade/nanopack"
)

// Field ID constants for SecureMessage, matching its `bin:"N"` struct tags.
const (
	SecureMessageFieldSenderID   uint8 = 1
	SecureMessageFieldRatchetKey uint8 = 2
	SecureMessageFieldNonce      uint8 = 3
	SecureMessageFieldCiphertext uint8 = 4
)

// MarshalBinID implements nanopack.BinMarshalerID.
func (p *SecureMessage) MarshalBinID(e *nanopack.Encoder) error {
	var scratch [8]byte
	e.AddID(SecureMessageFieldSenderID, []byte(p.SenderID))
	e.AddID(SecureMessageFieldRatchetKey, p.RatchetKey)
	if _, err := e.AddUint64ID(SecureMessageFieldNonce, p.Nonce, scratch[:]); err != nil {
		return err
	}
	e.AddID(SecureMessageFieldCiphertext, p.Ciphertext)
	return nil
}

// UnmarshalBinID implements nanopack.BinUnmarshalerID.
func (p *SecureMessage) UnmarshalBinID(fields []nanopack.FieldID) error {
	for _, f := range fields {
		switch f.ID {
		case SecureMessageFieldSenderID:
			p.SenderID = string(f.Data)
		case SecureMessageFieldRatchetKey:
			p.RatchetKey = f.Data
		case SecureMessageFieldNonce:
			if len(f.Data) != 8 {
				return nanopack.ErrShortBody
			}
			p.Nonce = binary.BigEndian.Uint64(f.Data)
		case SecureMessageFieldCiphertext:
			p.Ciphertext = f.Data
		}
	}
	return nil
}
